In [1]:
import pandas as pd

df = pd.read_csv("data/raw/grammys.csv")
df.head()

,annual_edition,year,award,artist,artist_link,producers,song_or_album,url,winner
0,1,1958,Album Of The Year,Van Cliburn,/artists/van-cliburn/16525,NaN,"Tchaikovsky: Concerto No. 1, In B-Flat Minor, ...",/awards/1st-annual-grammy-awards,False
1,1,1958,Album Of The Year,Frank Sinatra,/artists/frank-sinatra/6581,NaN,Only The Lonely (Album),/awards/1st-annual-grammy-awards,False
2,1,1958,Album Of The Year,Ella Fitzgerald,/artists/ella-fitzgerald/16685,NaN,Ella Fitzgerald Sings The Irving Berlin Song B...,/awards/1st-annual-grammy-awards,False
3,1,1958,Album Of The Year,Frank Sinatra,/artists/frank-sinatra/6581,NaN,Come Fly With Me (Album),/awards/1st-annual-grammy-awards,False
4,1,1958,Album Of The Year,Henry Mancini,/artists/henry-mancini/11935,NaN,The Music From Peter Gunn,/awards/1st-annual-grammy-awards,True

In [2]:
# select required columns
df = df[["year", "award", "artist", "song_or_album", "winner"]]
df.head()

,year,award,artist,song_or_album,winner
0,1958,Album Of The Year,Van Cliburn,"Tchaikovsky: Concerto No. 1, In B-Flat Minor, ...",False
1,1958,Album Of The Year,Frank Sinatra,Only The Lonely (Album),False
2,1958,Album Of The Year,Ella Fitzgerald,Ella Fitzgerald Sings The Irving Berlin Song B...,False
3,1958,Album Of The Year,Frank Sinatra,Come Fly With Me (Album),False
4,1958,Album Of The Year,Henry Mancini,The Music From Peter Gunn,True

In [3]:
# filter for rows that are from years 2016-2024
df = df[(df["year"] >= 2016) & (df["year"] <= 2024)]
print(df)

       year                                  award            artist  \
20957  2016                      Album Of The Year  Sturgill Simpson
20958  2016                      Album Of The Year             Drake
20959  2016                      Album Of The Year     Justin Bieber
20960  2016                      Album Of The Year           Beyoncé
20961  2016                      Album Of The Year             Adele
...     ...                                    ...               ...
25038  2024  Songwriter of the Year, Non-Classical               NaN
25039  2024  Songwriter of the Year, Non-Classical               NaN
25040  2024  Songwriter of the Year, Non-Classical               NaN
25041  2024  Songwriter of the Year, Non-Classical               NaN
25042  2024  Songwriter of the Year, Non-Classical               NaN

                   song_or_album  winner
20957  A Sailor's Guide To Earth   False
20958                      Views   False
20959                    Purpose   False
20960                   Lemonade   False
20961                         25    True
...                          ...     ...
25038                       RAYE   False
25039           Jessie Jo Dillon   False
25040              Edgar Barrera   False
25041            Jessi Alexander   False
25042                  Amy Allen    True

[4086 rows x 5 columns]

In [4]:
# rename song_or_album to music 
df = df.rename(columns={"song_or_album": "music"})
df.head()

,year,award,artist,music,winner
20957,2016,Album Of The Year,Sturgill Simpson,A Sailor's Guide To Earth,False
20958,2016,Album Of The Year,Drake,Views,False
20959,2016,Album Of The Year,Justin Bieber,Purpose,False
20960,2016,Album Of The Year,Beyoncé,Lemonade,False
20961,2016,Album Of The Year,Adele,25,True

In [5]:
# standardize music by removing descriptors: delete anything starting with "("
df["music"] = df["music"].str.split("(").str[0].str.strip()
print(df)

       year                                  award            artist  \
20957  2016                      Album Of The Year  Sturgill Simpson
20958  2016                      Album Of The Year             Drake
20959  2016                      Album Of The Year     Justin Bieber
20960  2016                      Album Of The Year           Beyoncé
20961  2016                      Album Of The Year             Adele
...     ...                                    ...               ...
25038  2024  Songwriter of the Year, Non-Classical               NaN
25039  2024  Songwriter of the Year, Non-Classical               NaN
25040  2024  Songwriter of the Year, Non-Classical               NaN
25041  2024  Songwriter of the Year, Non-Classical               NaN
25042  2024  Songwriter of the Year, Non-Classical               NaN

                           music  winner
20957  A Sailor's Guide To Earth   False
20958                      Views   False
20959                    Purpose   False
20960                   Lemonade   False
20961                         25    True
...                          ...     ...
25038                       RAYE   False
25039           Jessie Jo Dillon   False
25040              Edgar Barrera   False
25041            Jessi Alexander   False
25042                  Amy Allen    True

[4086 rows x 5 columns]

In [6]:
# only winners 
df = df[df["winner"] == True]
print(df)

       year                                  award          artist  \
20961  2016                      Album Of The Year           Adele
20966  2016                       Best Album Notes             NaN
20971  2016           Best Alternative Music Album     David Bowie
20976  2016        Best American Roots Performance    Sarah Jarosz
20981  2016               Best American Roots Song             NaN
...     ...                                    ...             ...
25016  2024        Producer Of The Year, Classical             NaN
25021  2024    Producer Of The Year, Non-Classical             NaN
25029  2024                     Record Of The Year  Kendrick Lamar
25037  2024                       Song Of The Year             NaN
25042  2024  Songwriter of the Year, Non-Classical             NaN

                                     music  winner
20961                                   25    True
20966  Sissle And Blake Sing Shuffle Along    True
20971                            Blackstar    True
20976                       House Of Mercy    True
20981                           Kid Sister    True
...                                    ...     ...
25016                       Elaine Martone    True
25021                         Daniel Nigro    True
25029                          Not Like Us    True
25037                          Not Like Us    True
25042                            Amy Allen    True

[785 rows x 5 columns]

In [7]:
# save clean dataset
df.to_csv("data/clean/grammys_clean.csv", index=False)