In [32]:
import pandas as pd

df = pd.read_csv("raw/grammys.csv")
df.head()

,annual_edition,year,award,artist,artist_link,producers,song_or_album,url,winner
0,1,1958,Album Of The Year,Van Cliburn,/artists/van-cliburn/16525,NaN,"Tchaikovsky: Concerto No. 1, In B-Flat Minor, ...",/awards/1st-annual-grammy-awards,False
1,1,1958,Album Of The Year,Frank Sinatra,/artists/frank-sinatra/6581,NaN,Only The Lonely (Album),/awards/1st-annual-grammy-awards,False
2,1,1958,Album Of The Year,Ella Fitzgerald,/artists/ella-fitzgerald/16685,NaN,Ella Fitzgerald Sings The Irving Berlin Song B...,/awards/1st-annual-grammy-awards,False
3,1,1958,Album Of The Year,Frank Sinatra,/artists/frank-sinatra/6581,NaN,Come Fly With Me (Album),/awards/1st-annual-grammy-awards,False
4,1,1958,Album Of The Year,Henry Mancini,/artists/henry-mancini/11935,NaN,The Music From Peter Gunn,/awards/1st-annual-grammy-awards,True

In [33]:
# select required columns
df = df[["year", "award", "artist", "song_or_album", "winner"]]
df.head()

,year,award,artist,song_or_album,winner
0,1958,Album Of The Year,Van Cliburn,"Tchaikovsky: Concerto No. 1, In B-Flat Minor, ...",False
1,1958,Album Of The Year,Frank Sinatra,Only The Lonely (Album),False
2,1958,Album Of The Year,Ella Fitzgerald,Ella Fitzgerald Sings The Irving Berlin Song B...,False
3,1958,Album Of The Year,Frank Sinatra,Come Fly With Me (Album),False
4,1958,Album Of The Year,Henry Mancini,The Music From Peter Gunn,True

In [34]:
# filter for rows that are from years 2016-2020
df = df[(df["year"] >= 2016) & (df["year"] <= 2020)]
print(df)

       year              award            artist              song_or_album  \
20957  2016  Album Of The Year  Sturgill Simpson  A Sailor's Guide To Earth
20958  2016  Album Of The Year             Drake                      Views
20959  2016  Album Of The Year     Justin Bieber                    Purpose
20960  2016  Album Of The Year           Beyoncé                   Lemonade
20961  2016  Album Of The Year             Adele                         25
...     ...                ...               ...                        ...
23098  2020   Song Of The Year               NaN                    Circles
23099  2020   Song Of The Year               NaN                   Cardigan
23100  2020   Song Of The Year               NaN                    The Box
23101  2020   Song Of The Year               NaN               Black Parade
23102  2020   Song Of The Year               NaN            I Can't Breathe

       winner
20957   False
20958   False
20959   False
20960   False
20961    True
...       ...
23098   False
23099   False
23100   False
23101   False
23102    True

[2146 rows x 5 columns]

In [43]:
# rename song_or_album to music and artist to artist_name
df = df.rename(columns={"song_or_album": "music_title",
                       "artist": "artist_name"})

df.head()

,year,award,artist_name,music_title,winner
20957,2016,Album Of The Year,Sturgill Simpson,A Sailor's Guide To Earth,False
20958,2016,Album Of The Year,Drake,Views,False
20959,2016,Album Of The Year,Justin Bieber,Purpose,False
20960,2016,Album Of The Year,Beyoncé,Lemonade,False
20961,2016,Album Of The Year,Adele,25,True

In [44]:
# standardize music by removing descriptors: delete anything starting with "("
df["music_title"] = df["music_title"].str.split("(").str[0].str.strip()
print(df)

       year               award       artist_name                music_title  \
20957  2016   Album Of The Year  Sturgill Simpson  A Sailor's Guide To Earth
20958  2016   Album Of The Year             Drake                      Views
20959  2016   Album Of The Year     Justin Bieber                    Purpose
20960  2016   Album Of The Year           Beyoncé                   Lemonade
20961  2016   Album Of The Year             Adele                         25
...     ...                 ...               ...                        ...
23090  2020  Record Of The Year          Doja Cat                     Say So
23091  2020  Record Of The Year            DaBaby                   Rockstar
23092  2020  Record Of The Year       Black Pumas                     Colors
23093  2020  Record Of The Year           Beyoncé               Black Parade
23094  2020  Record Of The Year     Billie Eilish        Everything I Wanted

       winner
20957   False
20958   False
20959   False
20960   False
20961    True
...       ...
23090   False
23091   False
23092   False
23093   False
23094    True

[1203 rows x 5 columns]

In [45]:
# check for missing values
missing_values = df.isnull().sum()
df = df.dropna()

dropped_missing_values = df.isnull().sum()
print(dropped_missing_values)

year           0
award          0
artist_name    0
music_title    0
winner         0
dtype: int64

In [46]:
# check size
df.shape

(1203, 5)

In [47]:
df.head()

,year,award,artist_name,music_title,winner
20957,2016,Album Of The Year,Sturgill Simpson,A Sailor's Guide To Earth,False
20958,2016,Album Of The Year,Drake,Views,False
20959,2016,Album Of The Year,Justin Bieber,Purpose,False
20960,2016,Album Of The Year,Beyoncé,Lemonade,False
20961,2016,Album Of The Year,Adele,25,True

In [48]:
# save clean dataset
df.to_csv("processed/grammys_clean.csv", index=False)